repos:
  # - repo: https://github.com/bridgecrewio/checkov
  #   rev: 2.0.910
  #   hooks:
  #     - id: checkov
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
      # - id: pretty-format-json
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v2.4.0"
  #   hooks:
  #     - id: prettier
