repos:
  # - repo: https://github.com/bridgecrewio/checkov
  #   rev: 2.0.910
  #   hooks:
  #     - id: checkov
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: detect-private-key
      # - id: pretty-format-json
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v2.4.0"
  #   hooks:
  #     - id: prettier
