---
- name: 'BGP config tasks'
  hosts: '{{ target | default("host_labfw") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Create Policy Export Rule
      paloaltonetworks.panos.panos_bgp_policy_rule:
        provider: '{{ device }}'
        vr_name: 'new-vrouter'
        name: 'test-rule-1'
        type: 'export'
        enable: true
        action: 'allow'
        address_prefix:
          - name: '10.10.10.0/24'
            exact: true
          - name: '192.168.0.0/16'
        action_community_type: 'append'
        action_community_argument: '100:10'
        used_by: 'network1'

    - name: Create import rule
      paloaltonetworks.panos.panos_bgp_policy_rule:
        provider: "{{ device }}"
        vr_name: "default"
        name: "rule-002"
        type: "import"
        address_prefix:
          - name: "10.2.2.0/24"
        enable: true
        action: "allow"

    - name: Create import rule 2
      paloaltonetworks.panos.panos_bgp_policy_rule:
        provider: "{{ device }}"
        vr_name: "default"
        name: "rule-001"
        type: "import"
        address_prefix:
          - name: "10.1.1.0/24"
        enable: true
        action: "allow"

    - name: Create export rule
      paloaltonetworks.panos.panos_bgp_policy_rule:
        provider: '{{ device }}'
        vr_name: 'new-vrouter'
        name: 'Export'
        type: 'export'
        used_by: ['network1', 'network2']
        action_as_path_type: 'remove'
        match_as_path_regex: '12345'
        action: 'allow'
