---
- name: Palo Alto Playbook
  hosts: '{{ target | default("host_labfw") }}'
  connection: local
  gather_facts: false

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Check if PAN-OS appliance is ready
      paloaltonetworks.panos.panos_check:
        provider: "{{ provider }}"
      changed_when: false
      register: result

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ result.msg }}"
