---
- name: Palo Alto Playbook
  hosts: '{{ target | default("host_labfw") }}'
  connection: local
  gather_facts: no

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Check if PAN-OS appliance is ready
      panos_check:
        provider: "{{ provider }}"
      changed_when: false
      register: result
      until: result is not failed and result.msg == 'Device is ready.'
      retries: 100
      delay: 15

    - name: Display output
      debug:
        msg: "{{ result.msg }}"