---
- name: Check Python packages
  hosts: '{{ target | default("firewall") }}'
  connection: local

  tasks:
    - name: Debug Python packages installed
      ansible.builtin.command: pip freeze
      register: packages
      changed_when: packages != 0

    - name: Display packages
      ansible.builtin.debug:
        msg: "{{ packages.stdout_lines }}"
