---
- name: Palo Alto Playbook
  hosts: '{{ target | default("homelabrama") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Commit candidate configuration
      # This module just covers commit of Panorama config from candidate to running, not push of config to managed devices
      paloaltonetworks.panos.panos_commit_panorama:
        provider: "{{ device }}"
      register: results
    - name: Print output
      ansible.builtin.debug:
        msg: "Commit with Job ID: {{ results.jobid }} had output: {{ results.details }}"
