---
- name: Palo Alto Playbook
  hosts: '{{ target | default("homelabrama") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Commit and Push template configuration
      # This module just covers push of config to managed devices, not commit of Panorama config from candidate to running
      paloaltonetworks.panos.panos_commit_push:
        provider: "{{ device }}"
        style: "device group"
        name: "{{ device_group }}"
        include_template: false
      register: results
    - name: Output
      ansible.builtin.debug:
        msg: "Job ID: {{ results.jobid }} finished"
