---
- name: Palo Alto Playbook
  hosts: '{{ target | default("host_homelabrama") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"
    devicegroups: ["poc-dg", "hq-dg"]

  tasks:
    - name: Commit and Push Device Group
      # This module just covers push of config to managed devices, not commit of Panorama config from candidate to running
      paloaltonetworks.panos.panos_commit_push:
        provider: "{{ device }}"
        style: "device group"
        name: "{{ item }}"
        include_template: false
        sync: false # Don't wait for job to finish, ensures loop goes as fast as possible
      loop: "{{ devicegroups }}"
