---
- name: Palo Alto Networks Playbook
  hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Read CSV file
      community.general.read_csv:
        path: test.csv
        key: hostname
      register: srcr1hosts

    - name: Display output
      ansible.builtin.debug:
        msg:
          - "{{ srcr1hosts.dict | dict2items }}"

    - name: Display output
      ansible.builtin.debug:
        msg:
          - "{{ item.value.hostname }}"
      with_items: "{{ srcr1hosts.dict | dict2items }}"

    - name: Display output
      ansible.builtin.debug:
        msg:
          - "{{ item.value.ip }}"
      with_items: "{{ srcr1hosts.dict | dict2items }}"

    - name: Create address objects
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        state: present
        name: "{{ item.value.hostname }}"
        value: "{{ item.value.ip }}"
      with_items: "{{ srcr1hosts.dict | dict2items }}"

    - name: Create list
      ansible.builtin.set_fact:
        hosts_in_group: "{{ srcr1hosts.dict | dict2items | map(attribute='key') | list }}"

    - name: Display output
      ansible.builtin.debug:
        msg:
          - "{{ hosts_in_group }}"

    - name: Add address objects to address group
      paloaltonetworks.panos.panos_address_group:
        provider: "{{ device }}"
        name: test_group
        state: present
        static_value: "{{ hosts_in_group }}"

    - name: Add a rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        state: "present"
        rule_name: "Test rule"
        source_zone: ["any"]
        destination_zone: ["any"]
        source_ip: ["test_group"]
        source_user: ["any"]
        destination_ip: ["any"]
        application: ["ssl"]
        action: "allow"
