---
- name: Export ops-related files
  hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Download Stats Dump file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "stats-dump"
        filename: "statsdump.tar.gz"

    - name: Download Device State file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "device-state"
        filename: "device-state.tgz"

    - name: Download Tech-Support file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "tech-support"
        filename: "tech-support.tgz"

    - name: Export cert with keys
      paloaltonetworks.panos.panos_export:
        provider: '{{ device }}'
        category: 'certificate'
        filename: 'cert.pem'
        certificate_name: 'my-cert'
        certificate_format: pem
        certificate_include_keys: true
        certificate_passphrase: 'somethingSecret'

    - name: Download filter PCAP file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "filter-pcap"
        filter_pcap_name: "rx"
        filename: "rx.pcap"

    - name: Download Application PCAP file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "application-pcap"
        application_pcap_name: "/20230213/192.168.150.17-17500-192.168.150.255-17500-163170.pcap"
        filename: "app.pcap"

    - name: Download Threat PCAP file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "threat-pcap"
        threat_pcap_id: "1152921504606876542"
        threat_pcap_search_time: "2023/02/22 11:47:30"
        filename: "threat.pcap"

    - name: Download DLP PCAP file
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "dlp-pcap"
        dlp_password: "somethingSecret"
        dlp_pcap_name: "20230213/192.168.150.49-59018-104.154.89.105-443-154006"
        filename: "dlp.pcap"
