---
- name: Palo Alto Playbook
  hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: A with_sequence -> loop
      ansible.builtin.debug:
        # testuser, % for formatting, 0 for 'fill' preceeding with zeros, 4 is minimum width of chars, d is decimal
        # https://docs.python.org/3/library/string.html#format-specification-mini-language
        msg: "{{ 'testuser%04d' | format(item) }}"
      # range is exclusive of the end point - start, end, gap
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-sequence
      loop: "{{ range(98, 104, 1) | list }}"

    - name: Add IPSec tunnels
      paloaltonetworks.panos.panos_ipsec_tunnel:
        provider: "{{ provider }}"
        name: "{{ 'autovpn%03d' | format(item) }}"
        tunnel_interface: "tunnel.1"
        ak_ike_gateway: "ike-gw"
        ak_ipsec_crypto_profile: "default"
      loop: "{{ range(98, 102, 1) | list }}"

    - name: Add IPSec IPv4 Proxy IDs
      paloaltonetworks.panos.panos_ipsec_ipv4_proxyid:
        provider: "{{ provider }}"
        name: "{{ 'proxyID%03d' | format(item) }}"
        tunnel_name: "{{ 'autovpn%03d' | format(item) }}"
        remote: "{{ '1.1.1.%1d' | format(item) }}"
      loop: "{{ range(98, 102, 1) | list }}"
