---
- name: OSPF config
  hosts: '{{ target | default("host_labfw") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"
    virtual_router_name: "new-vrouter"
    ospf_area: "5.5.5.5"
    network_interface: "ethernet1/1"
    router_id: "10.10.10.1"
    new_metric: 50

  collections:
    - paloaltonetworks.panos

  tasks:
    # Create OSPF config
    - name: OSPF config
      paloaltonetworks.panos.panos_config_element:
        provider: "{{ device }}"
        xpath: "/config/devices/entry[@name='localhost.localdomain']/network/virtual-router/entry[@name='{{ virtual_router_name }}']/protocol"
        element: >
          "<ospf>
          <enable>yes</enable>
          <area>
          <entry name='{{ ospf_area }}'>
          <type>
          <normal/>
          </type>
          <interface>
          <entry name='{{ network_interface }}'>
          <bfd><profile>Inherit-vr-global-setting</profile></bfd>
          <enable>yes</enable>
          <passive>no</passive>
          <gr-delay>10</gr-delay>
          <metric>10</metric>
          <priority>1</priority>
          <hello-interval>10</hello-interval>
          <dead-counts>4</dead-counts>
          <retransmit-interval>5</retransmit-interval>
          <transit-delay>1</transit-delay>
          <link-type><broadcast/></link-type>
          </entry></interface></entry>
          </area><router-id>{{ router_id }}</router-id>
          </ospf>"

    # Change OSPF interface metric
    - name: Change OSPF interface metric
      paloaltonetworks.panos.panos_config_element:
        provider: "{{ device }}"
        xpath: >
          "/config/devices/entry[@name='localhost.localdomain']/network/virtual-router/
          entry[@name='{{ virtual_router_name }}']/protocol/ospf/area/
          entry[@name='{{ ospf_area }}']/interface/
          entry[@name='{{ network_interface }}']/metric"
        element: "<metric>{{ new_metric }}</metric>"
        edit: true
