---
# panos_facts_more.yml - Gather seected bits of info from a PAN-OS device.
#
# Description
# ===========
#
# Uses various modules to gather data about a PAN-OS device.
#
# This playbook requires connection details for the device to be specified in the variables 'ip_address', 'username',
# and 'password'.  These may be defined as host variables (see `host_vars/firewall.yml` for an example) or
# extra vars.
#
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory panos_facts_more.yml

- name: Using panos_facts
  hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get security rules (facts)
      paloaltonetworks.panos.panos_security_rule_facts:
        provider: "{{ device }}"
        details: true
      register: sec_rules

    - name: Get general info (facts)
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"

    - name: Display security rules
      ansible.builtin.debug:
        msg:
          - "{{ sec_rules }}"

    - name: Display interfaces
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts['net_interfaces'] }}"

    - name: Display routes
      ansible.builtin.debug:
        msg:
          - "{{ ansible_facts['net_routing_table'] }}"
