---
- name: Gather rules
  hosts: '{{ target | default("host_vm-series-a") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get all address objects
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: addresobjects

    - name: Output
      ansible.builtin.debug:
        msg: "{{ addresobjects }}"
