---
- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

    # Hardcoded example variables
    from_zone: "home"
    dest_one: "1.1.1.1"
    dest_two: "2.2.2.2"
    egress_int: "ethernet1/3"
    monitor_ip: "8.8.8.8"
    monitor_profile: "default"
    next_hop: "192.168.150.1"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Check if firewall is ready
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: result

    - name: pbf policy
      panos_pbf_rule:
        provider: "{{ device }}"
        name: "the-pbf-rule"
        from_value: ["{{ from_zone }}"]
        destination_addresses: ["{{ dest_one }}", "{{ dest_two }}"]
        action: "forward"
        forward_egress_interface: "{{ egress_int}}"
        forward_next_hop_type: "ip-address"
        forward_monitor_profile: "{{ monitor_profile }}"
        forward_monitor_ip_address: "{{ monitor_ip }}"
        forward_next_hop_value: "{{ next_hop }}"
