---
- name: Playbook
  hosts: '{{ target | default("all") }}'
  gather_facts: false

  tasks:
    - name: Pre-flight check
      ansible.builtin.ping:

    - name: Ping across VPN to AWS - shell
      ansible.builtin.command: ping 172.31.100.158
      ignore_errors: true
