---
- name: Playbook
  hosts: '{{ target | default("all") }}'
  gather_facts: false

  vars:
    ping_count: 1

  tasks:
    - name: Pre-flight check
      ansible.builtin.ping:

    - name: Ping across VPN to AWS - shell
      ansible.builtin.command: ping 172.31.100.158 -c {{ ping_count }}
